### ISSUE TITLE
should be "View All Products"

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#104]
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/cc7b9960-7ffd-468f-b23d-82c90fba03c5)

**Comment by VikassWebkul214254** [comment]
Resolved

**Comment by anais-enclavewrx** [comment]
this is a laptop view, it should be "View All Products"

**Comment by VikassWebkul214254** [comment]
Resolved
[iPhone-11-192.168.15.214-MRS-c39drc.webm](https://github.com/jn-devops/rli-bagisto/assets/107629725/a2b5b0cd-a016-4919-b476-9c52203c028f)

**Comment by anais-enclavewrx** [comment]
should be "Products"
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/f55ed338-c85d-46f4-a1a7-78b65b639cb9)
