### ISSUE TITLE
Copy of Variant

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#106]
Why are we seeing the copy of a variant? Also, the bulk uploader is still not working.

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/bcaf579b-fa8f-4e52-96b1-cd0a8c369881)

**Comment by VikassWebkul214254** [comment]
We need to debug code on server. please share ssh details.

Becouse i have not found issue on local instance.


https://github.com/jn-devops/rli-bagisto/assets/107629725/92260487-e189-4708-9508-476b7e877997

**Comment by anais-enclavewrx** [comment]
Hi can we have your SSH key, I'll connect you on our server.

**Comment by VikassWebkul214254** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqUCuoI+HJc9HUZoCJaD8GSgcE9y1r2c1Bl4UkY7KlH1NqcXq7mdr4uEkcAD/8X6vJRYdWVuPcHDzbna59SH7flVMoSwreZvBe2tdGwxYLAiJ52fV+ztjDzBzAjhZ9l7edgBws5Af4cBBvaTtJ7rs9PZ5105DfdroAAMq2CdCs4vS+WiJF/51X3dAnIx2AJnEtO5ZtHTlWaM2IpuBnn2+KJ3mWeNo9ESKfjiQD4GhrftTspAUixVxR0ifYMVHLvUPYq+lZgdxQqmllyIBk7x5nWLSd0m7G6QmZ4jWU4UAutI7EBfQObS15P9ENcq0UsWRMwP33MVn0cnXtppmYm72J1j/uRer4L9uYphDC1wj25iX8Ol+wbWwNGSgxt0Da0d251nExv69Vb+QXpcXWzfRptZDOt7xkxJStMpHMQXbZyxT/1y9hMXV6dl+bTTwpEv7m1bvc3DmxmJtB7YmANm5pBwMN2rFsM+SOzWhDlPIQRPrxCBF2U++OXS/Nwu/fiT0= vikas.vishwakarma@vikas214
