### ISSUE TITLE
Disable News not working

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#107]
[screen-capture (5).webm](https://github.com/jn-devops/rli-bagisto/assets/122261359/d329c59f-e7ce-44e5-8e25-ec9b21ef41ba)

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/e3f3813b-d089-4cc5-a371-442f15022504)

**Comment by VikassWebkul214254** [comment]
Resolved
