### ISSUE TITLE
Change default filter to "Newest First" on Category Page

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#113]
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/e0cecda3-81c4-44b9-aea2-a4012bb1f878)

**Comment by VikassWebkul214254** [comment]
For this goto https://shop.homeful.ph/admin/configuration/catalog/products. in this page have Storefront settign. under the Storefront have Sort By field. there you can select any option. that option will display  first into dropdown and product list will sort according this.
