### ISSUE TITLE
View All Products Page

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#114]
Where can we remove/add filters on all products page?

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/918e8794-fae4-4695-9699-4c7b051ca55e)

**Comment by VikassWebkul214254** [comment]
Under attribute edit/create page have  ```Use in Layered Navigation``` options. if you checked then attribute will display filter section else not display.

![attribute-edit-create](https://github.com/jn-devops/rli-bagisto/assets/107629725/c894d7eb-2743-4295-a404-f9941a0ea8fa)
