### ISSUE TITLE
Product Images number of display

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#115]
Please add two more containers for product images before displaying +1 on images. Also, do not limit the number of images that can be uploaded.

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/969dc2f5-49e3-40e1-a75a-cccef0395033)

**Comment by anais-enclavewrx** [comment]
This is for Laptop/Bigger screen only.

**Comment by VikassWebkul214254** [comment]
Resolved

**Comment by VikassWebkul214254** [comment]
this issue fixed. please check and closed it.
