### ISSUE TITLE
Product Image Modal Display

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#116]
Please reduce the padding top/margin top, move the 'x' button to the corner. The button's appearance seems off. Do not stretch the images. Thanks!

laptop
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/424c46c2-5990-417e-bd25-d501ca4cd12b)

iPad

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/5cfbcba1-43c0-495b-92a6-c59854c5e198)

mobile
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/2ce0fda3-b149-4bd4-993b-56fb67f5fc04)

**Comment by VikassWebkul214254** [comment]
Resolved

**Comment by VikassWebkul214254** [comment]
![tablet](https://github.com/jn-devops/rli-bagisto/assets/107629725/a465515e-cce4-4d43-9d01-c8e536b848ad)
![mobile](https://github.com/jn-devops/rli-bagisto/assets/107629725/6d15dbd7-9a44-484a-943b-da8f1e59f1c4)
![product_1](https://github.com/jn-devops/rli-bagisto/assets/107629725/9d7c376d-9acb-494a-8d6f-08260de538cf)

**Comment by anais-enclavewrx** [comment]
images were too stretched on mobile and iPad view, can you make it look better? Thank you!

**Comment by VikassWebkul214254** [comment]
https://github.com/jn-devops/rli-bagisto/assets/107629725/5bab6202-d2f8-4fc2-afcc-682d112f4124

resolved
