### ISSUE TITLE
BULK UPLOAD - Images & Description

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#117]
Some images and long product descriptions didn't upload correctly in the latest bulk uploader. Here's the latest bulk uploader.

[bulk_uploader (4).xlsx](https://github.com/user-attachments/files/15511834/bulk_uploader.4.xlsx)

**Comment by VikassWebkul214254** [comment]
please check with below file.

we removed some extra value.
[bulk_uploader.4.xlsx](https://github.com/user-attachments/files/15514393/bulk_uploader.4.xlsx)

**Comment by anais-enclavewrx** [comment]
Hi, 
Some images and long product descriptions still didn't upload correctly.

[screen-capture (7).webm](https://github.com/jn-devops/rli-bagisto/assets/122261359/1c06ac85-6367-4631-857d-5ba1ee87bb7a)

**Comment by anais-enclavewrx** [comment]
how can we make the description look like this?  it seems like the description became a paragraph.

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/76c3f978-fc91-4a92-bb82-d15ce9e85aac)

**Comment by anais-enclavewrx** [comment]
Also please check on our end why we can't see the updated description and images. Thank you!

**Comment by VikassWebkul214254** [comment]
please share 

> how can we make the description look like this? it seems like the description became a paragraph.
> 
> ![image](https://private-user-images.githubusercontent.com/122261359/336301740-76c3f978-fc91-4a92-bb82-d15ce9e85aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzczODEsIm5iZiI6MTcxNzQ3NzA4MSwicGF0aCI6Ii8xMjIyNjEzNTkvMzM2MzAxNzQwLTc2YzNmOTc4LWZjOTEtNGE5Mi1iYjgyLWQxNWNlOWU4NWFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNDU4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGI3MDA0ZTExNjE3MzRjNzkzZDM0MjE0YjI2MTE4M2NhMjM1ODQzMjU5MDljNzlkZWZhYTJhNTRlMDMzN2ZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fQpIDIbgJaQ55zAOAvbPw7bhiBn96T_3ILMNS8eVMTM)

please share as test here.

**Comment by VikassWebkul214254** [comment]
> Also please check on our end why we can't see the updated description and images. Thank you!

=> As we check server supervisor is not configured and also i did not configure it.
Why important it? because we are using laravel job for product update/create with cdn image upload and supervisor will run these jobs.

For More Details: https://laravel.com/docs/11.x/queues#supervisor-configuration

Note: Without supervisor product will not update.
I also informed over task and github.

**Comment by anais-enclavewrx** [comment]
Supervisor access has been given since february. Kindly check it again on your end, thank you! Also, Bulk uploader issue has been resolved. Thank you. We will create a design in figma for the long description.

**Comment by VikassWebkul214254** [comment]
> how can we make the description look like this? it seems like the description became a paragraph.
> 
> ![image](https://private-user-images.githubusercontent.com/122261359/336301740-76c3f978-fc91-4a92-bb82-d15ce9e85aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODc0ODYsIm5iZiI6MTcxNzQ4NzE4NiwicGF0aCI6Ii8xMjIyNjEzNTkvMzM2MzAxNzQwLTc2YzNmOTc4LWZjOTEtNGE5Mi1iYjgyLWQxNWNlOWU4NWFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNzQ2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDk1N2Q2MDhlMzExYWQ0NGMyMGFmMjk1YzllNDc0YTAzMDkwYTk3YjdlNTE3YjRhZmY3ZmNhZDQwYzdiN2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ryE_dhZ1d5eOC2fzW1087LVib43M4jLIa-Eoljt8V4I)



For this you can details in html format as below.


```
<p>
    <strong>House Features:</strong>
</p>
<ul>
    <li>Semi-complete turnover.</li> 
    <li>2 car park provision.</li> 
    <li>Living and dining area with tiles.</li> 
    <li>Kitchen with counter and sink.</li> 
    <li>1 toilet and bath with tiles.</li> 
    <li>Provision for 3 bedrooms.</li> 
</ul>

<p>
    <strong>Amenities:</strong>
</p>
<ul>
    <li>Swimming pool.</li>
    <li>Chapel</li> 
    <li>Basketball court</li> 
    <li>Landscaping</li> 
    <li>Parks and playground</li> 
    <li>Guarded entrances</li> 
    <li>Perimeter fence</li> 
</ul>

<p>
    <strong>House Turnover:</strong>
</p>
<ul> 
    <li>Ground Floor: Kitchen with countertop and base cabinet, complete toilet and bath, floor with vitrified ceramic tiles, glass sliding door to carport (provision).</li>
    <li>Second Floor: Ceiling included, provision for three bedrooms, floor ready to receive tiles.</li> 
</ul>

<p>
    <strong>Accessible Location:</strong>
</p>
<ul> 
    <li>5 mins from iMall</li> 
    <li>5 mins from Don Bosco</li> 
    <li>7 mins from HM Transport Terminal</li> 
    <li>10 mins from SLEX</li> 
    <li>20 mins from SM Calamba</li> 
    <li>25 mins from Nuvali</li> 
    <li>30 mins from Alabang Festival Mall</li> 
    <li>At Agapeya Towns, your success is reflected in every detail. Discover a home where every element ensures you feel rewarded for your hard work.&nbsp;</li> 
</ul>
```

![file-bulk-upload](https://github.com/jn-devops/rli-bagisto/assets/107629725/d3ff0eb7-c4cc-47d7-a37e-d082a7b7800d)
![product-page](https://github.com/jn-devops/rli-bagisto/assets/107629725/2ccc9a96-0899-4f8f-a054-86b6ba06fb25)

**Comment by anais-enclavewrx** [comment]
Thank you!
