### ISSUE TITLE
TEXT AREA for Verification Page

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#119]
Hi! Please create a text area for this. Thank you!

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/eb382c1f-ee9d-4149-9cae-60a54d55d23d)

**Comment by VikassWebkul214254** [comment]
First Run Below Cmd:

```
php artisan db:seed --class="Webkul\\Ekyc\\Database\\Seeders\\CMSPageSeeder"
```

And Go to CMS section and check ```url-key=verify-page```. also we will provide button setting.

![cms-pages](https://github.com/jn-devops/rli-bagisto/assets/107629725/2ad13bbd-450f-48c5-9525-97627e2d07fd)


![edit-page](https://github.com/jn-devops/rli-bagisto/assets/107629725/0dd4546b-6426-4145-8c71-4cc23dbdc347)
