### ISSUE TITLE
remove brand on product page

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#121]
please remove this part, it is redundant, thank you.

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/c7b6511d-a17a-42cb-bbc9-b2613413fd81)

**Comment by VikassWebkul214254** [comment]
Under attribute edit/create page have ```Visible on Product View Page``` on Front-end option. if you checked then attribute will display on product page else not display.

**Comment by VikassWebkul214254** [comment]
this is not an issue

**Comment by anais-enclavewrx** [comment]
Thank you!
