### ISSUE TITLE
BULK UPLOADER

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#142]
I've tried the bulk uploader again, but no products were displayed even after an hour. Kindly resolve this issue. For your reference the product is Agapeya Towns. Thank you.

**Comment by VikassWebkul214254** [comment]
please share excel..

**Comment by VikassWebkul214254** [comment]
did you upload ?
[668e48663f8fd.xlsx](https://github.com/user-attachments/files/16159090/668e48663f8fd.xlsx)

**Comment by VikassWebkul214254** [comment]
Hello,

Product Uploaded On server. we found that configurable product's  name and slug same as category. make sure category and product name is diffrent. that why system have confuse  to make Redirect URL.

[668e48663f8fd.xlsx](https://github.com/user-attachments/files/16159285/668e48663f8fd.xlsx)

Find the Updated Excel

**Comment by anais-enclavewrx** [comment]
Got it, now all the category should include the word "category" so that the system won't be confused. Thank you Vikas! will try the Bulk Uploader again today.

**Comment by VikassWebkul214254** [comment]
> category

welcome. make supe category name match between Database and excel. let us know if have found any issue.
