### ISSUE TITLE
Enclaves Theme

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#148]
Following your installation instructions, we have successfully migrated from shop.homeful.ph to homeful.ph and published the Enclaves vendor. However, upon completion of these steps, it appears that certain sections of our Enclaves theme are now missing. You can verify this at https://homeful.ph/ for your reference.

We kindly request your assistance in resolving this matter, and we would greatly appreciate your prompt attention to this issue.

Thank you for your assistance.

**Comment by VikassWebkul214254** [comment]
Please close this issue. if resolved
