### ISSUE TITLE
Getting the Ui issue on product list page, When viewed on the Ipad/mobile devices.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#80]
**eCommerce CRM Sync**

**Description:**

Getting the UI issue on the product list page, when it is viewed on iPad or mobile devices.

**Actual Result**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 1 eCommerce CRM Sync may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/bc225c7e-8029-4111-9b85-3e0f482cbb54)

**Comment by VikassWebkul214254** [comment]
https://prnt.sc/YiegPzsT-ZQM

Resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. Please check the Screenshot/Video below.

**Attached video/screenshot for future reference**

![issue 80 closed eCommerce may 22](https://github.com/jn-devops/rli-bagisto/assets/163374765/711fdef8-e523-44a6-9cee-b3ebd7a51dfe)
