### ISSUE TITLE
Getting the UI issue on the text.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#81]
**eCommerce CRM Sync**

**Description:**

Getting the UI issue on the text.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 2 ecommerce CRM may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/a84c81cf-b034-4214-a995-1cf79c4cef16)

**Comment by VikassWebkul214254** [comment]
https://prnt.sc/Nn5yuqs-6Fwe

Resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. Please check the Screenshot/Video below.

**Attached the Screenshot/Video for Future reference:**

![issue 81 fixed eCommerce may 22](https://github.com/jn-devops/rli-bagisto/assets/163374765/30813dc8-4226-4179-a30d-a73335bbc401)
