### ISSUE TITLE
Please update the arrow icons per the Figma design.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#82]
**eCommerce CRM Sync:**

**Description:**

Please update the arrow icons per the Figma design.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 3 ecommerce may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/9781ea83-66f0-4cc4-b173-064179a0d2df)

**Comment by VikassWebkul214254** [comment]
resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.

**Attached video/screenshot for future reference**


https://github.com/jn-devops/rli-bagisto/assets/163374765/f5628ebb-d85a-4b14-888f-bffd64bb9311
