### ISSUE TITLE
Getting the UI issue on the front text section, When viewed on mobile devices.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#83]
**eCommerce CRM Sync:**

**Description:**

Getting the UI issue on the front text section, When viewed on mobile devices.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 4 ecommerce may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/080c15da-d4ca-4079-8a7c-f63d194ab143)

**Comment by VikassWebkul214254** [comment]
deplicate issue https://github.com/jn-devops/rli-bagisto/issues/81

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.

**Attached video/screenshot for future reference**


https://github.com/jn-devops/rli-bagisto/assets/163374765/48375274-cd26-4a37-b68d-ec77cf8f47d9
