### ISSUE TITLE
Rename the "Choose Unit" button to "Choose Area" button.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#85]
**eCommerce CRM Sync:**

**Description:**

Rename the "Choose Unit" button to "Choose Area" button.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 6 ecommerce may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/574ba5fe-0d64-448a-a94d-06719881cfff)

**Expected Result:**

The button name "Choose Unit" should display the "Choose Area."

**Comment by anais-enclavewrx** [comment]
Apologies, please do not change this one. It should read "Choose Unit." I will revise the Figma for better understanding.

**Comment by VikassWebkul214254** [comment]
@harshit-webkul please close  this issue

**Comment by harshit-webkul** [comment]
After a discussion with @VikassWebkul214254 sir, no need to change the name, So I am closing this issue.
