### ISSUE TITLE
The logo should be displayed per the Figma design, Please increase the icon size.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#86]
**eCommerce CRM Sync:**

**Description:**

The logo should be displayed per the Figma design, Please increase the icon size.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 7 ecommerce may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/40c7dc80-2815-435d-933a-06a481e1b475)

**Comment by VikassWebkul214254** [comment]
i also informed on task for image size. please check with required size of image.
