### ISSUE TITLE
The sort filter is not working on the category page. According to the sort filter, only the amount and name are changed, but the image is not.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#87]
**eCommerce CRM Sync:**

**Description:**

The sort filter is not working on the category page. According to the sort filter, only the amount and name are changed, but the image is not.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

https://github.com/jn-devops/rli-bagisto/assets/163374765/98a88a64-289e-4fa1-9782-c92c51a07347

**Comment by VikassWebkul214254** [comment]
Resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.

**Attached video/screenshot for future reference**


https://github.com/jn-devops/rli-bagisto/assets/163374765/68ffe1a5-99bc-46ee-8323-db902b5ff2b9
