### ISSUE TITLE
Getting the UI issue on the customer dashboard section, When viewed on 100% size but It is displayed fine on 75% size.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#88]
**eCommerce CRM Sync:**

**Description:**

Getting the UI issue on the customer dashboard section, When viewed on 100% size but It is displayed fine on 75% size.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 9 ecommerce may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/eb361d8e-6938-4936-9d80-de91927aba92)

**Figma Design:**

![figma design issue 9](https://github.com/jn-devops/rli-bagisto/assets/163374765/70900732-e8b0-47c6-ac86-fcd828a43412)

**Comment by VikassWebkul214254** [comment]
resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.

**Attached video/screenshot for future reference**


https://github.com/jn-devops/rli-bagisto/assets/163374765/3fc58efd-3c3a-45e0-8773-6afdae3db3f2
