### ISSUE TITLE
Please redesign the Customer Profile section on the front.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#89]
**eCommerce CRM Sync:**

**Description:**

Please redesign the Customer Profile section on the front.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 10 ecommerce may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/6d305bcb-7b6e-4c74-bd97-d923a07817fa)

**Expected Result:**

The customer Profile section should be shown as the Figma design.

**Comment by VikassWebkul214254** [comment]
@harshit-webkul tab available into forms. click fill out the form button first.

**Comment by VikassWebkul214254** [comment]
https://prnt.sc/q8bAaC28ihqO

Resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.

**Attached video/screenshot for future reference**


https://github.com/jn-devops/rli-bagisto/assets/163374765/8acef81c-167e-4a6e-894b-aa1f5577c1ee
