### ISSUE TITLE
Gettign the UI issue on Inquries ->> Submit A Ticket section.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#90]
**eCommerce CRM Sync:**

**Description:**

Getting the UI issue on Inquiries ->> Submit A Ticket section.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 11 ecommerce may 21](https://github.com/jn-devops/rli-bagisto/assets/163374765/2ef02fab-7e18-4fb4-9927-494b6ebec691)

**Comment by VikassWebkul214254** [comment]
https://prnt.sc/Zph5nhEipYZn

resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.
