### ISSUE TITLE
URGENT - Remove property details under the Product Image

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#92]
Please refer to the image. Kindly remove the ground floor, end unit, and unit type. Retain the bedroom, bathroom and carport, if the value is zero, do not show it.

Thanks.

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/646c4f56-99f5-4bb0-976a-1000f3a47ec4)

**Comment by VikassWebkul214254** [comment]
Resolved

**Comment by anais-enclavewrx** [comment]
> Resolved

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/12dbafd6-5a5c-4133-a3d0-953703818dcd)
please remove the unit type, replace it with carport, and if the value of carport is 0, do not show it. Thanks

**Comment by VikassWebkul214254** [comment]
@anais-enclavewrx for Unit type: please rename unit type to carport from backend under attribute section.
![front-edn](https://github.com/jn-devops/rli-bagisto/assets/107629725/285d9ca4-0cd6-4eab-bf43-69d3536b9bff)
![attribute](https://github.com/jn-devops/rli-bagisto/assets/107629725/eef2e0de-9df5-419c-a4dc-c3ab1fa18c50)

**Comment by VikassWebkul214254** [comment]
![property](https://github.com/jn-devops/rli-bagisto/assets/107629725/e9717cc6-b60b-483b-92ac-c9a450f68419)

**Comment by VikassWebkul214254** [comment]
@anais-enclavewrx closed this issue if issue resolved.

**Comment by anais-enclavewrx** [comment]
Please provide numerical responses instead of yes or no, such as "2" for the number of bathrooms. Your answers should align with the options available in our bulk uploader.

**Comment by anais-enclavewrx** [comment]
The unit type attribute offers options for "house and lot" or "condo," rather than a binary choice of yes or no. Therefore, we shouldn't alter it to "carport." Could we enable customization of the product page to allow selection of which attributes to display?

**Comment by VikassWebkul214254** [comment]
> Please provide numerical responses instead of yes or no, such as "2" for the number of bathrooms. Your answers should align with the options available in our bulk uploader.
 
=> You can fill value in file under the bedroom columns. it will display as same in product page.

![1](https://github.com/jn-devops/rli-bagisto/assets/107629725/589cabbb-b23c-453c-8a5c-333909dc4236)

> Could we enable customization of the product page to allow selection of which attributes to display?
=> Under attribute edit/create page have  `Visible on Product View Page on Front-end` option. if you checked then attribute will display on product page else not display.

![2](https://github.com/jn-devops/rli-bagisto/assets/107629725/02261e92-9f5b-4238-a469-7f607211657a)

**Comment by anais-enclavewrx** [comment]
> @anais-enclavewrx for Unit type: please rename unit type to carport from backend under attribute section. ![front-edn](https://private-user-images.githubusercontent.com/107629725/333167928-285d9ca4-0cd6-4eab-bf43-69d3536b9bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzIxMzcsIm5iZiI6MTcxNjk3MTgzNywicGF0aCI6Ii8xMDc2Mjk3MjUvMzMzMTY3OTI4LTI4NWQ5Y2E0LTBjZDYtNGVhYi1iZjQzLTY5ZDM1MzZiOWJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwODM3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTM2NDc4NzA1OTcwNWM5ZjFjOTVmOWViYjlmMGRiY2I0YWI3ODE1NDgxMDExYTBkM2M0Y2VjNzBmNDgwMTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ppwd98faD69TCLnz9lXYT4NxDlr0aOEiwU8fT3w3lV0) ![attribute](https://private-user-images.githubusercontent.com/107629725/333167942-eef2e0de-9df5-419c-a4dc-c3ab1fa18c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzIxMzcsIm5iZiI6MTcxNjk3MTgzNywicGF0aCI6Ii8xMDc2Mjk3MjUvMzMzMTY3OTQyLWVlZjJlMGRlLTlkZjUtNDE5Yy1hNGRjLWMzYWIxZmExOGM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwODM3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjFhNjkxOGM5MGI5ODA0OTE2ZDUzYWYwMmI4ZjgxNDA1M2QyODQ5MzhkNGExMmJlYTlhYmMyZWIxMWY0ZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O-sIplYJJuisqWXyTA66-oAivD41iULvtfALHLPPfCk)

we shouldn't rename the unit_type because it reflects the options "condominium and house and lot" just show the carports attribute under the product image and remove the unit_type

here's the carports
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/b492eae2-07ca-4280-adc4-0084ab34749a)

here's the unit_type
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/3fc798fa-209e-491d-bf08-0e743ab58b2c)

do not show the unit type here, instead show the carports
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/6538f5d4-2c97-4cf1-9d91-61a68770d447)

**Comment by VikassWebkul214254** [comment]
we removed Unit Type from code. if you want add other attribute so please share here we will add into code.

**Comment by VikassWebkul214254** [comment]
![Uploading propertys.png…]()

**Comment by VikassWebkul214254** [comment]
![propertys](https://github.com/jn-devops/rli-bagisto/assets/107629725/e1be650e-f8fe-4f71-8fa8-9d406d719e02)

**Comment by anais-enclavewrx** [comment]
Please add lot area and floor area. Thanks!
