### ISSUE TITLE
URGENT - Bulk Uploader Error

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#95]
![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/d7f9da74-7bab-44b1-a341-7a4acd626b91)
Hi, I'm trying to check if the uploader for the images is working, but I have this error. I'm using the attached excel, you can test it on your end.
[bulk_uploader_4.xlsx](https://github.com/jn-devops/rli-bagisto/files/15402405/bulk_uploader_4.xlsx)

**Comment by VikassWebkul214254** [comment]
@anais-enclavewrx  issue resolved.


https://github.com/jn-devops/rli-bagisto/assets/107629725/458b865f-fe01-4721-9d50-64ace6c4c27e

**Comment by anais-enclavewrx** [comment]
[screen-capture (4).webm](https://github.com/jn-devops/rli-bagisto/assets/122261359/0885e7c1-84df-4558-99d7-1a9cc103f50e)
 
I'm still having an issue

**Comment by anais-enclavewrx** [comment]
Please review the error message and ensure that image uploading functionality is working properly as well.

**Comment by VikassWebkul214254** [comment]
@anais-enclavewrx I have check color attribute code is not same as in file.
![attribute](https://github.com/jn-devops/rli-bagisto/assets/107629725/b773b440-34c0-4711-addc-b8fcb4c880da)

Also please provide shop.homeful.ph ssh details on task. we need to debug the code.

**Comment by anais-enclavewrx** [comment]
We didn't add that attribute. I've deleted it now to avoid confusion.

**Comment by VikassWebkul214254** [comment]
ok. 

please open .env file and upadte QUEUE_DRIVER  `sync` to `database`. after that run optimize cmd.

**Comment by VikassWebkul214254** [comment]
informed over the task.

**Comment by anais-enclavewrx** [comment]
Thank you Vikas!
