### ISSUE TITLE
Change the " Hopeful" text to "Homeful", remove the background color, and Reposition the "View All Products" button to match the Figma design on mobile devices.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#96]
**eCommerce CRM Sync:**

**Description:**

Change the " Hopeful" text to "Homeful", remove the background color, and Reposition the "View All Products" button to match the Figma design on mobile devices.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

![new issue 96 eCommerce may 22 ](https://github.com/jn-devops/rli-bagisto/assets/163374765/bdbc4d2d-c657-43da-ab82-732e1c1a8c70)

**Figma design:**

![issue 96 reference eCommerce](https://github.com/jn-devops/rli-bagisto/assets/163374765/04dad94f-7b8f-4f0d-978b-faf8a0aa7119)

**Comment by VikassWebkul214254** [comment]
Resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.

**Attached video/screenshot for future reference**

![issue 96 closed eCommerce may 29](https://github.com/jn-devops/rli-bagisto/assets/163374765/00423b02-8136-44f9-a256-b641a8079017)
