### ISSUE TITLE
  When viewed on mobile devices ->> click the profile icon. The login section should be displayed in the desktop view.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#97]
**eCommerce CRM Sync:**

**Description:**

 When viewed on mobile devices ->> click the profile icon. The login section should be displayed in the desktop view.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

**On mobile view**

![new issue 97 eCommerce may 22](https://github.com/jn-devops/rli-bagisto/assets/163374765/9f0197e3-f322-441e-995f-dcca87e91117)

**On desktop View:**

![issue 97 reference eCommerce may 22](https://github.com/jn-devops/rli-bagisto/assets/163374765/66d6fbec-392b-40e3-a64f-3b6f71cd57dd)

**Comment by VikassWebkul214254** [comment]
Resolved
