### ISSUE TITLE
 When the product is removed from the Shopping/mini cart, the pop-up message is not displayed correctly.

### ISSUE THREAD

**Issue by harshit-webkul** [jn-devops/rli-bagisto#98]
**eCommerce CRM Sync:**

**Description:**

When the product is removed from the Shopping/mini cart, the pop-up message is not displayed correctly.

**Actual Result:**

Please Consider the Screenshot/Video for a better understanding of the issues.

https://github.com/jn-devops/rli-bagisto/assets/163374765/91a994c6-7061-41bf-b548-5321ac111ff9

**Comment by VikassWebkul214254** [comment]
![Screenshot from 2024-05-23 19-04-33](https://github.com/jn-devops/rli-bagisto/assets/107629725/6f05be3d-2974-4d68-ab18-4758358918de)

**Comment by VikassWebkul214254** [comment]
Resolved

**Comment by harshit-webkul** [comment]
Checked and verified that the issue has been resolved. So I am closing this issue.

**Attached video/screenshot for future reference**

![Screenshot from 2024-05-24 18-50-48](https://github.com/jn-devops/rli-bagisto/assets/163374765/a68a60aa-fd53-4c8f-9ec7-a98b8e37a12e)
